/**
 * @createTime 2015-04-13
 * @author louis.tru <louistru@live.com>
 * @copyright (C) 2011 louis.tru, http://mooogame.com
 * @version 1.0
 */
 
// teide/touch/Dialog.vx
ts.set_tags([
  '确定',
'OK',
  '取消',
'Cancel',
  '全部',
'All',
  '本地',
'Local',
// teide/touch/AddMenu.vx
  '添加新文件',
'Add New File',
  '添加新目录',
'Add New Directory',
  '添加Zip压缩文件', 
'Add Zip Compress File',
//   '添加FTP/SFTP目录', 
// 'Add FTP/SFTP Directory',
  '添加FTP/SFTP/SVN', 
'Add FTP/SFTP/SVN',
  '添加SSH远程脚本', 
'Add SSH remote script',
  '从Web服务器下载', 
'Download from the Web',
  '下载GitHub项目', 
'Download from the GitHub',
// client/teide/touch/AddMenu.js
  '文件',
'File',
  '目录',
'Directory',
  '无法添加,当前有任务没有完成!', 
'Unable appended, task is not finished currently.',
  '输入新的文件名称',
'Input a new file name',
  '文件名称不能为空或特殊字符',
'File name can not as null or special character',
  '输入新的目录名称',
'Input a new directory',
  '目录名称不能为空或特殊字符',
'Directory can not as null or special character',
  '请先创建一个本地目录',
'Please create a local directory',
  '无法添加,当前有任务没有完成!',
'Unable appended, task is not finished currently',
  '检测到您刚刚添加了映射配置,是否立即从服务器更新目录',
'Detected you just appended the map configuration, do you want to update the directory from server ',
  '无法下载,当前有任务没有完成!',
'Unable download, task is not finished currently.',
  '下载失败,请检查网络环境或下载地址是否有效',
'Download failure, please check network environment or download link is available or not.',
  '下载的文件似乎是个压缩包,是否尝试解压?',
'It looks like that download file is a ZIP package, do you want to unzip it?',
  '无法下载,当前有任务没有完成!',
'Unable download, task is not finished currently.',
  '输入要下载的文件URL',
'Input the URL which you want to download.',
  '请输入正确的URL',
'Please input the right URL',
  '无法下载,当前有任务没有完成!',
'Unable download, task is not finished currently.',
  '输入GitHub项目路径',
'Input GitHub project path',
  '请输入正确的GitHub项目路径',
'Please input the right GitHub project path',
  '确定要下载\n{0}',
'Sure you want to Download\n{0}',
  '停止下载',
'Stop Download',
  '停止提交',
'Stop Submit',
  '停止更新',
'Stop Update',
  '停止克隆',
'Stop Clone',
  '停止删除',
'Stop Delete',
// client/teide/touch/FileInfoMenu.js
  '改名',
'Rename',
  '克隆',
'Clone',
  '删除',
'Delete',
  '搜索',
'Search',
  '解压',
'Unzip',
  '更新',
'Update',
  '加入',
'Join',
  '提交',
'Submit',
  '解决',
'Solve',
  '解锁',
'Unlock',
  '清理',
'Cleanup',
  '发送',
'Send',
  '输入新的名称',
'Input a new name',
  '名称不能为空或特殊字符',
'Name can not as null or special character',
  '无法提交,当前有任务没有完成!',
'Unable submit, task is not finished currently',
  '无法更新,当前有任务没有完成!',
'Unable update, task is not finished currently',
  '无法重命名,当前有任务没有完成!',
'Unable rename, task is not finished currently',
  '无法克隆,当前有任务没有完成!',
'Unable Clone, task is not finished currently',
  '是否要删除 {0} ?',
'Do you want to delete {0} ?',
  '是否要删除 {0}, 删除本地或者全部 ?',
'Do you want to delete {0}, delete local or all ?',
  '无法删除,当前有任务没有完成!',
'Unable delete, task is not finished currently',
  '无法加入,当前有任务没有完成!',
'Unable add, task is not finished currently',
  '无法提交,当前有任务没有完成!',
'Unable submit, task is not finished currently',
  '确定要将变化提交到服务器吗?',
'Are you sure to save the updates into server?',
  '当前还有{0}个冲突没有解决,确定要将变化提交到服务器吗?',
'{0} conflicts still not solved, are you sure to save the updates into server?',
  '无法提交,当前有{0}个冲突没有解决,是否查看冲突日志?',
'Unable to submit, {0} conflicts still not solved, to see conflict log?',
  '无法解决冲突,当前有任务没有完成!',
'Unable to solve conflicts, task is not finished currently',
  '无法解锁,当前有任务没有完成!',
'Unable unlock, task is not finished currently',
  '无法清理,当前有任务没有完成!',
'Unable cleanup, task is not finished currently',
// client/teide/touch/MainViewport.js
  '无法编辑,当前有任务没有完成!',
'Unable to edit, task is not finished currently',
  '无法完成编辑,当前有任务没有完成!',
'Unable to finish edit, task is not finished currently',
  '不是有效的可运行文件',
'Invalid executable file',
  '当前没有打开的可运行文件',
'No executable file running',
  '请先打开一个可运行的文件',
'Please open an executable file',
  '运行异常详情请见控制台日志',
'Abnormal operation details please see console log',
// client/teide/touch/MainViewport.vx
  '完成',
'Done',
// client/teide/touch/MoreMenu.js
  '无法解压,当前有任务没有完成!',
'Unable unzip, task is not finished currently',
  '只有zip文件才能被解压缩',
'Only zip file can be unzipped',
  '解压缩文件失败',
'Unzip failure',
//   'Touch Code 保持唤醒状态下用浏览器打开以下地址,可上传与下载文件',
// 'Touch Code keep activate then use explorer to open below address, you can upload and download file',
  'Touch Code 保持唤醒状态用浏览器打开',
'Touch Code keep activate then use explorer to open',
  '检测到设备没有连接到网络,请先将设备连接到网络',
'Equipment is not connecting with network, please connect it first.',
  '检测到设备没有连接到网络,请先将设备连接到wifi网络',
'Equipment is not connecting with network, please connect with WIFI first.',
  '无法压缩,当前有任务没有完成!',
'Unable compress, task is not finished currently',
  '请选择要压缩的文件或目录',
'Please choose the file or directory to compress',
  '压缩文件失败',
'Compress file failure',
  '请选择要解压的文件',
'Please choose a file to unzip',
  '无法刷新目录,当前有任务没有完成!',
'Unable refresh directory, task is not finished currently',
  '关于',
'About',
  '刷新目录',
'Refresh',
  '连接到当前设备',
'Connect to This',
  '停止解压',
'Stop Unzip',
  '停止压缩',
'Stop Compress',
  '偏好设置',
'Preferences',
  '文件服务',
'File Service',
// client/teide/touch/SearchPanel.js
  '查询表达式格式错误,如果只是普通查询可禁用正则表达式',
'Query expression format is wrong, if you only do general search then you can forbid the regular expression.',
  '正在搜索中',
'Searching',
  '没有找到任何匹配项',
'Unable to find any matching item.',
// client/teide/touch/SearchPanel.vx
  '搜索',
'Search',
  '搜索更多',
'Searching more',
  '停止搜索',
'Stop searching',
//  # Menu start
  '搜索全部文件',
'Searching all files',
  '搜索指定文件',
'Searching appoint file',
  '忽略大小写',
'Ignore case',
  '启用正则表达式',
'Enabled RegExp',
  '启用隐藏文件搜索',
'Hiding file searching',
  '展开全部搜索结果',
'Unfold all the result',
// client/teide/touch/FileContentView.vx
  '自动换行',
'Word Wrap',
  '使用16号字体',
'Use Font Size 16',
  '显示行号',
'Show Line Numbers',
  '使用2空格缩进',
'Use Space Indent 2',
  '启用触摸焦点',
'Enable Touch Focus',
  '折叠/展开全部',
'Toggle Fold All',
  '触摸焦点',
'Touch Focus',
  '缩进宽度',
'Indent Width',
  '显示制表符',
'Show Invisibles',
  '字体大小',
'Font Size',
  '主题',
'Theme',
  '显示缩进向导',
'Show Indent Guides',
// Other
  '查看文档', 
'View Document',
  '未知',
'Unknown',
// 
  '无法移动,当前有任务没有完成!',
'Unable move, task is not finished currently.',
  '更新版本冲突,是否要查看日志信息?',
'Update file version conflict, Do you want to see the log?',
  'Preferences Settings',
'Preferences Settings',
  '明亮',
'Bright',
  '黑暗',
'Dark',
  '初始编辑器',
'Initial editor',
  '设置为只读',
'Set to read only',
  '激活全部功能',
'Activate all',
  '将此软件推荐给5个好友并安装,便可免费拥有全部功能',
'The software to recommend with five friends and install, you can free possess all functional',
  '打开此开关,触摸代码编辑器可立即弹出软键盘',
'Turning this switch, touch the code editor immediately exhaled the soft keyboard',
  '可供多达30多种主题风格的选择',
'For up to 30 several themed selection',
  '您的支持是我前进的动力,是否要去评价此软件?',
'Your support is the driving force of my progress, whether to evaluate the software?',
  '提交建议与BUG',
'Suggest and BUG',
  '评价此软件',
'Reviews Software',
  '我的ID',
'My ID',
  '推荐人ID',
'Introducer ID',
  '注意: 推荐人ID设置后不能更改',
'Note: Introducer ID settings after can not be changed',
  '输入ID',
'Input ID',
  '搜索关键字',
'Search keywords',
  '推荐人ID设置后不能更改,确定要设置为"{0}"?',
'Introducer ID settings after can not be changed,\nsure you want to set it to "{0}"?',
  '你的输入不正确,标识长度应不小于6并且不大于12的16进制字符串',
'Your input is not correct, ID length should be no less than six and no greater than twelve of hex string',
  '不能将自己设置为推荐人',
'Cannot set yourself to introducer',
  '现在无法使用此功能,请购买Ph版或Pro版.\n或将此软件推荐给5个好友可免费激活,现在就去激活吗?',
"Can't use this functional now, please buy the Ph/Pro version "+
'or recommend this software to five friends can be free to activate, now go to activate?',
  '购买Ph版',
'Buy Ph version',
  '购买专业版',
'Buy Pro version',
]);

// ace Localization
ts.set_tags([
  'Copy',
'Copy',
  'Cut',
'Cut',
  'Paste',
'Paste',
  'Select',
'Select',
  'Select Line',
'Select Line',
  'Select All',
'Select All',
  'Find',
'Find',
  'Open',
'Open',
  'Prev',
'Prev',
  'Next',
'Next',
  'Fold',
'Fold',
  'Unfold',
'Unfold',
]);